# Generated by Django 5.2.6 on 2026-02-21 09:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speaking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakingrequest",
            name="checklist",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured checklist data sent with the request.",
            ),
        ),
        migrations.AddField(
            model_name="speakingrequest",
            name="full_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="speakingrequest",
            name="payment_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date/time student made the payment.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="speakingrequest",
            name="phone_number",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="speakingrequest",
            name="telegram_username",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="speakingrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("connected", "Connected"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
